service: coffee-shop-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "dynamodb:*"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
functions:
  createCoffee:
    handler: src/handlers/createCoffee.handler
    events:
      - http:
        path: coffees
        method: post

  getCoffee:
    handler: src/handlers/gtCoffee.handler
    events:
      - http:
        path: coffees/{id}
        method: get

  updateCoffee:
    handler: src/handlers/updateCoffee.handler
    events: 
      - http:
        path: coffees/{id}
        method: put
  
  deleteCoffee:
    handler: src/handlers/deleteCoffee.handler
    events:
      - http:
        path: coffees/{id}
        method: delete

resources:
  Resources:
    CoffeeTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
